# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-03 01:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gerenciador', '0003_riscos'),
    ]

    operations = [
        migrations.AddField(
            model_name='riscos',
            name='projeto',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='gerenciador.Projeto'),
            preserve_default=False,
        ),
    ]
