# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-06 00:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gerenciador', '0005_auto_20171005_0221'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tarefa',
            name='sucessor',
        ),
        migrations.AddField(
            model_name='projeto',
            name='horasdia',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='projeto',
            name='sabado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tarefa',
            name='inicio',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='tarefa',
            name='subtarefade',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subtarefa', to='gerenciador.Tarefa'),
        ),
        migrations.RemoveField(
            model_name='tarefa',
            name='antecessor',
        ),
        migrations.AddField(
            model_name='tarefa',
            name='antecessor',
            field=models.ManyToManyField(null=True, related_name='_tarefa_antecessor_+', to='gerenciador.Tarefa'),
        ),
    ]
