# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-06 00:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gerenciador', '0006_auto_20171006_0013'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tarefa',
            old_name='subtarefade',
            new_name='subtarefas',
        ),
    ]
