# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-06 00:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gerenciador', '0007_auto_20171006_0031'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tarefa',
            name='subtarefas',
        ),
        migrations.AddField(
            model_name='tarefa',
            name='subtarefas',
            field=models.ManyToManyField(null=True, related_name='_tarefa_subtarefas_+', to='gerenciador.Tarefa'),
        ),
    ]
