# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-06 00:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gerenciador', '0008_auto_20171006_0036'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tarefa',
            name='subtarefas',
        ),
        migrations.AddField(
            model_name='tarefa',
            name='subtarefade',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subtarefa', to='gerenciador.Tarefa'),
        ),
    ]
