# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-06 01:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gerenciador', '0009_auto_20171006_0039'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projeto',
            name='sabado',
        ),
        migrations.RemoveField(
            model_name='tarefa',
            name='inicio',
        ),
    ]
