# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-12 11:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gerenciador', '0010_auto_20171006_0110'),
    ]

    operations = [
        migrations.AddField(
            model_name='projeto',
            name='datainicio',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='projeto',
            name='descricao',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='projeto',
            name='pessoas',
            field=models.ManyToManyField(related_name='pessoas', to='gerenciador.Pessoa'),
        ),
        migrations.AlterField(
            model_name='tarefa',
            name='antecessor',
            field=models.ManyToManyField(related_name='_tarefa_antecessor_+', to='gerenciador.Tarefa'),
        ),
    ]
