# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-13 02:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gerenciador', '0011_auto_20171012_1101'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='ordem',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tarefa',
            name='falha',
            field=models.BooleanField(default=False),
        ),
    ]
