# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-13 16:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gerenciador', '0012_auto_20171013_0244'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projeto',
            name='pessoas',
        ),
        migrations.AddField(
            model_name='projeto',
            name='pessoa',
            field=models.ManyToManyField(to='gerenciador.Pessoa'),
        ),
        migrations.AlterField(
            model_name='tarefa',
            name='falha',
            field=models.BooleanField(default=False, verbose_name='Apenas em caso de falha'),
        ),
        migrations.AlterField(
            model_name='tarefa',
            name='subtarefade',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subtarefa', to='gerenciador.Tarefa', verbose_name='Subtarefa De'),
        ),
    ]
