# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-13 22:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gerenciador', '0013_auto_20171013_1602'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projeto',
            name='horasdia',
        ),
        migrations.AlterField(
            model_name='tarefa',
            name='duracao',
            field=models.IntegerField(null=True, verbose_name='Duracao(em dias)'),
        ),
    ]
