# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-13 23:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gerenciador', '0014_auto_20171013_2244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarefa',
            name='antecessor',
            field=models.ManyToManyField(related_name='ant', to='gerenciador.Tarefa'),
        ),
    ]
