# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-17 00:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gerenciador', '0015_auto_20171013_2308'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tarefa',
            name='falha',
        ),
        migrations.AddField(
            model_name='tarefa',
            name='solucao',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gerenciador.Riscos', verbose_name='Solucao para'),
        ),
    ]
